use app::Event;

/// BlueZ Agent capabilities.
///
/// See:
/// <https://bluez.readthedocs.io/en/latest/agent-api/#agent-manager-hierarchy>
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AgentCapability {
    DisplayOnly,
    DisplayYesNo,
    KeyboardOnly,
    NoInputNoOutput,
    KeyboardDisplay,
}

impl AgentCapability {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::DisplayOnly => "DisplayOnly",
            Self::DisplayYesNo => "DisplayYesNo",
            Self::KeyboardOnly => "KeyboardOnly",
            Self::NoInputNoOutput => "NoInputNoOutput",
            Self::KeyboardDisplay => "KeyboardDisplay",
        }
    }
}

impl AsRef<str> for AgentCapability {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}

impl std::fmt::Display for AgentCapability {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Requests emitted by the D-Bus backend and handled by the Bluetooth UI.
///
/// Some variants are informational and only require the UI to display data.
/// Others require the UI to respond with a `BluetoothResponse`, which the
/// backend forwards to BlueZ.
///
/// **Display-only variants** — the backend replies to BlueZ before emitting
/// the event; the UI only needs to display the information:
/// - `DisplayPinCode`: BlueZ provides the generated PIN.
/// - `DisplayPasskey`: BlueZ reports the passkey and how many digits have been
///   entered on the remote device.
///
/// **Input-request variants** — the backend keeps the D-Bus method call
/// pending until the UI responds with a `BluetoothResponse`:
/// - `RequestPinCode`: Prompt the user for a legacy Bluetooth PIN.
/// - `RequestPasskey`: Prompt the user for a 6-digit numeric passkey.
///
/// **Confirmation variants** — the backend keeps the D-Bus method call pending
/// until the UI accepts or rejects the request:
/// - `RequestConfirmation`: Confirm that the displayed passkey matches.
/// - `RequestAuthorization`: Authorize the remote device.
/// - `AuthorizeService`: Authorize access to a Bluetooth service UUID.
///
/// **Cancellation**
/// - `Cancel`: BlueZ cancelled the pending interaction; the UI should dismiss
///   any open Bluetooth dialogs.
#[derive(Debug, Clone)]
pub enum BluetoothRequest {
    /// Request a legacy Bluetooth PIN from the user.
    RequestPinCode { device: String },

    /// Display a PIN generated by BlueZ.
    DisplayPinCode { device: String, pincode: String },

    /// Request a 6-digit numeric passkey from the user.
    RequestPasskey { device: String },

    /// Display a passkey and the number of digits entered on the remote device.
    DisplayPasskey {
        device: String,
        passkey: u32,
        entered: u16,
    },

    /// Ask the user to confirm that the displayed passkey matches.
    RequestConfirmation { device: String, passkey: u32 },

    /// Ask the user whether to authorize the remote device.
    RequestAuthorization { device: String },

    /// Ask the user whether to authorize access to a Bluetooth service.
    AuthorizeService { device: String, uuid: String },

    /// Cancel any pending UI interaction.
    Cancel,
}

impl Event for BluetoothRequest {}

/// Response emitted by the Bluetooth UI to satisfy a pending
/// `BluetoothRequest`.
#[derive(Debug)]
pub struct BluetoothResponse {
    pub outcome: BluetoothOutcome,
}

impl Event for BluetoothResponse {}

/// User action returned by the Bluetooth UI in response to a
/// `BluetoothRequest`.
#[derive(Debug, Clone)]
pub enum BluetoothOutcome {
    /// User approved the request.
    Accepted,

    /// User entered a legacy Bluetooth PIN.
    PinCode(String),

    /// User entered a numeric Bluetooth passkey.
    Passkey(u32),

    /// User dismissed a display-only dialog.
    Dismissed,

    /// User rejected the request.
    Rejected,
}
