[[atlas]]
name = "ui"

[[atlas.font]]
name = "inter"
path = "../../assets/Inter-Regular.ttf"
sizes = [14, 16, 24, 100]

[[atlas.font]]
name = "mono"
path = "../../assets/RobotoMono-Regular.ttf"
sizes = [14, 16, 24, 32, 48, 56, 64, 100]
